sudo: required
services:
  - docker
language: go
go:
  - 1.16.x
install:
  - go get -u github.com/vbatts/git-validation
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - mv kubectl ${GOPATH}/bin
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-$(uname)-amd64
  - chmod +x ./kind
  - mv ./kind ${GOPATH}/bin
jobs:
  include:
    - stage: PR Verify & e2e tests
      script: 
        - make pr-verify
    - script: 
        - make pr-test
after_script:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin;
      make push-mock-sdk-server;
    fi
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - eng@portworx.com
    on_success: change
    on_failure: always
