kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openstorage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openstorage-sc
  