kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: openstorage-sc
provisioner: csi.openstorage.org
parameters:
    repl: "1"
    csi.storage.k8s.io/provisioner-secret-name: token-secret
    csi.storage.k8s.io/provisioner-secret-namespace: default
    csi.storage.k8s.io/node-publish-secret-name: token-secret
    csi.storage.k8s.io/node-publish-secret-namespace: default

