on:
  pull_request:
    branches:
      - master
    types: ["closed"]

jobs:
  cherry_pick_release_9.4:
    runs-on: ubuntu-latest
    name: Cherry pick into release-9.4
    if: contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-9.4')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-9.4
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-9.4
          labels: |
            cherry-pick
  cherry_pick_release_9.3:
    runs-on: ubuntu-latest
    name: Cherry pick into release-9.3
    if: contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-9.3')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-9.3
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-9.3
          labels: |
            cherry-pick
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}